// PRODUCT DETAILS TEMPLATE
export const columns = [
  { key: 'sku', header: 'Sku' },
  { key: 'title', header: 'Title' },
  { key: 'description', header: 'Description' },
  { key: 'asin', header: 'Asin' },
  { key: 'fnsku', header: 'Fnsku' },
  { key: 'barcode', header: 'Barcode' },
  { key: 'supplier', header: 'Supplier' },
  { key: 'brand', header: 'Brand' },
  { key: 'category', header: 'Category' },
  { key: 'weight', header: 'Weight' },
  { key: 'length', header: 'Length' },
  { key: 'width', header: 'Width' },
  { key: 'height', header: 'Height' },
  { key: 'boxQty', header: 'Boxqty' },
  { key: 'boxWeight', header: 'Boxweight' },
  { key: 'boxLength', header: 'Boxlength' },
  { key: 'boxWidth', header: 'Boxwidth' },
  { key: 'boxHeight', header: 'Boxheight' },
  // { key: 'activeState', header: 'Activestate' },
  { key: 'note', header: 'Note' },
  { key: 'htsCode', header: 'HTS Code' },
  { key: 'defaultPrice', header: 'Defaultprice' },
  { key: 'msrp', header: 'Msrp' },
  { key: 'map', header: 'Map' },
  { key: 'floor', header: 'Floor' },
  { key: 'ceilling', header: 'Ceilling' },
  { key: 'sellerCost', header: 'Sellercost' },
  { key: 'inboundShippingCost', header: 'Inboundshippingcost' },
  { key: 'otherCosts', header: 'Othercosts' },
  { key: 'productionTime', header: 'Productiontime (Days)' },
  { key: 'transitTime', header: 'Transittime (Days)' },
  { key: 'shippingToFBACost', header: 'Shippingtofbacost' },
  { key: 'buffer', header: 'Buffer' },
  { key: 'itemCondition', header: 'Itemcondition' },
  { key: 'image', header: 'Image' },
  { key: 'recommendedDaysOfStock', header: 'Days Of Stock' },
]

export const columnsProductsFile = [
  { key: 'title', header: 'Title' },
  { key: 'sku', header: 'Sku' },
  { key: 'qty', header: 'Inventory' },
  // { key: 'description', header: 'Description' },
  // { key: 'asin', header: 'Asin' },
  // { key: 'fnsku', header: 'Fnsku' },
  // { key: 'barcode', header: 'Barcode' },
  // { key: 'supplier', header: 'Supplier' },
  // { key: 'brand', header: 'Brand' },
  // { key: 'category', header: 'Category' },
  // { key: 'weight', header: 'Weight' },
  // { key: 'length', header: 'Length' },
  // { key: 'width', header: 'Width' },
  // { key: 'height', header: 'Height' },
  // { key: 'boxQty', header: 'Boxqty' },
  // { key: 'boxWeight', header: 'Boxweight' },
  // { key: 'boxLength', header: 'Boxlength' },
  // { key: 'boxWidth', header: 'Boxwidth' },
  // { key: 'boxHeight', header: 'Boxheight' },
  // { key: 'htsCode', header: 'HTS Code' },
  // { key: 'defaultPrice', header: 'Defaultprice' },
  // { key: 'msrp', header: 'Msrp' },
  // { key: 'map', header: 'Map' },
  // { key: 'floor', header: 'Floor' },
  // { key: 'ceilling', header: 'Ceilling' },
  // { key: 'sellerCost', header: 'Sellercost' },
  // { key: 'inboundShippingCost', header: 'Inboundshippingcost' },
  // { key: 'otherCosts', header: 'Othercosts' },
  // { key: 'productionTime(Days)', header: 'Productiontime (Days)' },
  // { key: 'transitTime(Days)', header: 'Transittime (Days)' },
  // { key: 'shippingToFBACost', header: 'Shippingtofbacost' },
  // { key: 'buffer', header: 'Buffer' },
  // { key: 'itemCondition', header: 'Itemcondition' },
  // { key: 'image', header: 'Image' },
  // { key: 'note', header: 'Note' },
]

export const blankProducts = Array(30).fill({
  sku: '',
  title: '',
  description: '',
  asin: '',
  fnsku: '',
  barcode: '',
  supplier: '',
  brand: '',
  category: '',
  weight: '',
  length: '',
  width: '',
  height: '',
  boxQty: '',
  boxWeight: '',
  boxLength: '',
  boxWidth: '',
  boxHeight: '',
  // activeState: '',
  note: '',
  htsCode: '',
  defaultPrice: '',
  msrp: '',
  map: '',
  floor: '',
  ceilling: '',
  sellerCost: '',
  inboundShippingCost: '',
  otherCosts: '',
  productionTime: '',
  transitTime: '',
  shippingToFBACost: '',
  buffer: '',
  itemCondition: '',
  image: '',
  recommendedDaysOfStock: '',
})

// REFERENCE DATA TEMPLATE
export const columnsReferenceData = [
  { key: 'suppliers', header: 'Suppliers' },
  { key: 'brands', header: 'Brands' },
  { key: 'categories', header: 'Categories' },
  { key: 'conditions', header: 'Conditions' },
]
export const CONDITIONS = ['Conditions', 'New', 'Used']

// COLUMN INFO TEMPLATE
export const columnsInfo = [
  { key: 'label', header: 'Label' },
  { key: 'description', header: 'Description' },
  { key: 'example', header: 'Example' },
  { key: 'value', header: 'Value' },
]

export const columnsInfoData = [
  {
    label: '**',
    description: 'In order to upload file, you must save the Product Details Template Sheet as a CSV file.',
    example: '',
    value: '',
  },
  {
    label: '**',
    description: '',
    example: '',
    value: '',
  },
  {
    label: 'SKU',
    description: `Unique Identifier for product. No white spaces allowed. It cannot be changed once created. Invalid special characters: " ' @ ~ , ...`,
    example: 'PRODUCT-SKU-SIZE-COLOR',
    value: 'LOCKED',
  },
  {
    label: 'Title',
    description: `The title of the item as it should be displayed on the website. Max character limit of 150 characters (including spaces). Invalid special characters: " ' @ ~ , ...`,
    example: '',
    value: 'REQUIRED',
  },
  {
    label: 'Description',
    description:
      'The copy that appears on the product page. Long Description/Romance Copy must be an editorial statement about the product, not just the brand name. 250 character maximum (including spaces).',
    example: '',
    value: 'RECOMMENDED',
  },
  {
    label: 'Asin',
    description:
      'Amazon Standard Identification Number (ASIN) is a 10-character alphanumeric unique identifier assigned by Amazon.com and its partners for product identification within the Amazon organization. Invalid special characters: " \' @ ~ , ...',
    example: 'B0764JXVL8',
    value: 'IF AVAILABLE',
  },
  {
    label: 'Fnsku',
    description: 'Amazon Fulfillment Network Stock Keeping Unit (FNSKU).',
    example: '',
    value: 'IF AVAILABLE',
  },
  {
    label: 'Barcode',
    description: '12 Digit product identifier. Barcode found in the product packaging.',
    example: '736983029218',
    value: 'LOCKED',
  },
  {
    label: 'Supplier',
    description: 'The supplier of the product. The supplier must be in the reference data.',
    example: '',
    value: 'RECOMMENDED',
  },
  {
    label: 'Brand',
    description: 'The brand of the product. The brand must be in the reference data.',
    example: '',
    value: 'RECOMMENDED',
  },
  {
    label: 'Category',
    description: 'The category of the product. The category must be in the reference data.',
    example: '',
    value: 'RECOMMENDED',
  },
  {
    label: 'Weight',
    description: 'Product weight in pounds.',
    example: '10.3',
    value: 'LOCKED',
  },
  {
    label: 'Length',
    description: 'Product length in inches.',
    example: '29.5',
    value: 'LOCKED',
  },
  {
    label: 'Width',
    description: 'Product width in inches.',
    example: '9.5',
    value: 'LOCKED',
  },
  {
    label: 'Height',
    description: 'Product height in inches.',
    example: '9.5',
    value: 'LOCKED',
  },
  {
    label: 'Boxqty',
    description: 'Number of products in a master box.',
    example: '2',
    value: 'LOCKED',
  },
  {
    label: 'Boxweight',
    description: 'Master box weight in pounds.',
    example: '20.4',
    value: 'LOCKED',
  },
  {
    label: 'Boxlength',
    description: 'Master box length in inches.',
    example: '30',
    value: 'LOCKED',
  },
  {
    label: 'Boxwidth',
    description: 'Master box width in inches.',
    example: '20',
    value: 'LOCKED',
  },
  {
    label: 'Boxheight',
    description: 'Master box height in inches.',
    example: '10',
    value: 'LOCKED',
  },
  // {
  //   label: 'Activestate',
  //   description: 'The state of the product. Active: TRUE or Inactive: FALSE The state must be in the reference data.',
  //   example: 'TRUE',
  //   value: 'REQUIRED',
  // },
  {
    label: 'Note',
    description: 'Any notes about the product.',
    example: '',
    value: '',
  },
  {
    label: 'htsCode',
    description: 'HTS Code',
    example: '6603.20.3000',
    value: 'RECOMMENDED',
  },
  {
    label: 'Defaultprice',
    description: 'Product price.',
    example: '89.3',
    value: 'RECOMMENDED',
  },
  {
    label: 'Msrp',
    description: 'Manufacturer Suggested Retail Price.',
    example: '56.7',
    value: 'RECOMMENDED',
  },
  {
    label: 'Map',
    description: 'Minimum Advertised Price.',
    example: '50.4',
    value: 'RECOMMENDED',
  },
  {
    label: 'Floor',
    description: 'Minimum Sale price.',
    example: '48.9',
    value: 'RECOMMENDED',
  },
  {
    label: 'Ceilling',
    description: 'Maximum Sale price.',
    example: '110.5',
    value: 'RECOMMENDED',
  },
  {
    label: 'Sellercost',
    description: 'Seller cost.',
    example: '30.54',
    value: 'RECOMMENDED',
  },
  {
    label: 'Inboundshippingcost',
    description: 'Shipping cost to the warehouse.',
    example: '7.39',
    value: 'RECOMMENDED',
  },
  {
    label: 'Othercosts',
    description: 'Other product costs.',
    example: '0',
    value: 'RECOMMENDED',
  },
  {
    label: 'Productiontime',
    description: 'Time to produce the product in days after the purchase order has been created.',
    example: '15',
    value: 'RECOMMENDED',
  },
  {
    label: 'Transittime',
    description: 'Time to ship the product to the warehouse in days after the product is already produce.',
    example: '35',
    value: 'RECOMMENDED',
  },
  {
    label: 'Shippingtofbacost',
    description: 'Shipping cost to the FBA warehouse.',
    example: '1.5',
    value: 'RECOMMENDED',
  },
  {
    label: 'Buffer',
    description: 'Quantity of products to keep in stock.',
    example: '3',
    value: 'RECOMMENDED',
  },
  {
    label: 'Itemcondition',
    description: 'The condition of the product. The condition must be in the reference data.',
    example: 'NEW',
    value: 'RECOMMENDED',
  },
  {
    label: 'Image',
    description: 'Product image URL.',
    example: '',
    value: 'REQUIRED',
  },
  {
    label: 'Days Of Stock',
    description: 'Days of Stock after lead time.',
    example: '',
    value: 'RECOMMENDED',
  },
]

export const columnsInfoBlankData = [
  {
    label: '**',
    description: 'With this template you can add 30 new products.',
    example: '',
    value: '',
  },
  {
    label: '**',
    description: 'In order to add a more products, you must add a new row to the last row in the table.',
    example: '',
    value: '',
  },
  {
    label: '**',
    description: 'In order to upload file, you must save the Product Details Template Sheet as a CSV file.',
    example: '',
    value: '',
  },
  {
    label: '**',
    description: '',
    example: '',
    value: '',
  },
  {
    label: 'SKU',
    description: `Unique Identifier for product. No white spaces allowed. It cannot be changed once created. Invalid special characters: " ' @ ~ , ...`,
    example: 'PRODUCT-SKU-SIZE-COLOR',
    value: 'REQUIRED',
  },
  {
    label: 'Title',
    description: `The title of the item as it should be displayed on the website. Max character limit of 150 characters (including spaces). Invalid special characters: " ' @ ~ , ...`,
    example: '',
    value: 'REQUIRED',
  },
  {
    label: 'Description',
    description:
      'The copy that appears on the product page. Long Description/Romance Copy must be an editorial statement about the product, not just the brand name. 250 character maximum (including spaces).',
    example: '',
    value: 'RECOMMENDED',
  },
  {
    label: 'Asin',
    description:
      'Amazon Standard Identification Number (ASIN) is a 10-character alphanumeric unique identifier assigned by Amazon.com and its partners for product identification within the Amazon organization. Invalid special characters: " \' @ ~ , ...',
    example: 'B0764JXVL8',
    value: 'IF AVAILABLE',
  },
  {
    label: 'Fnsku',
    description: 'Amazon Fulfillment Network Stock Keeping Unit (FNSKU).',
    example: '',
    value: 'IF AVAILABLE',
  },
  {
    label: 'Barcode',
    description: '12 Digit product identifier. Barcode found in the product packaging.',
    example: '736983029218',
    value: 'REQUIRED',
  },
  {
    label: 'Supplier',
    description: 'The supplier of the product. The supplier must be in the reference data.',
    example: '',
    value: 'RECOMMENDED',
  },
  {
    label: 'Brand',
    description: 'The brand of the product. The brand must be in the reference data.',
    example: '',
    value: 'RECOMMENDED',
  },
  {
    label: 'Category',
    description: 'The category of the product. The category must be in the reference data.',
    example: '',
    value: 'RECOMMENDED',
  },
  {
    label: 'Weight',
    description: 'Product weight in pounds.',
    example: '10.3',
    value: 'RECOMMENDED',
  },
  {
    label: 'Length',
    description: 'Product length in inches.',
    example: '29.5',
    value: 'RECOMMENDED',
  },
  {
    label: 'Width',
    description: 'Product width in inches.',
    example: '9.5',
    value: 'RECOMMENDED',
  },
  {
    label: 'Height',
    description: 'Product height in inches.',
    example: '9.5',
    value: 'RECOMMENDED',
  },
  {
    label: 'Boxqty',
    description: 'Number of products in a master box.',
    example: '2',
    value: 'RECOMMENDED',
  },
  {
    label: 'Boxweight',
    description: 'Master box weight in pounds.',
    example: '20.4',
    value: 'RECOMMENDED',
  },
  {
    label: 'Boxlength',
    description: 'Master box length in inches.',
    example: '30',
    value: 'RECOMMENDED',
  },
  {
    label: 'Boxwidth',
    description: 'Master box width in inches.',
    example: '20',
    value: 'RECOMMENDED',
  },
  {
    label: 'Boxheight',
    description: 'Master box height in inches.',
    example: '10',
    value: 'RECOMMENDED',
  },
  // {
  //   label: 'Activestate',
  //   description: 'The state of the product. Active: TRUE or Inactive: FALSE The state must be in the reference data.',
  //   example: 'TRUE',
  //   value: 'REQUIRED',
  // },
  {
    label: 'Note',
    description: 'Any notes about the product.',
    example: '',
    value: '',
  },
  {
    label: 'htsCode',
    description: 'HTS Code',
    example: '6603.20.3000',
    value: 'RECOMMENDED',
  },
  {
    label: 'Defaultprice',
    description: 'Product price.',
    example: '89.3',
    value: 'RECOMMENDED',
  },
  {
    label: 'Msrp',
    description: 'Manufacturer Suggested Retail Price.',
    example: '56.7',
    value: 'RECOMMENDED',
  },
  {
    label: 'Map',
    description: 'Minimum Advertised Price.',
    example: '50.4',
    value: 'RECOMMENDED',
  },
  {
    label: 'Floor',
    description: 'Minimum Sale price.',
    example: '48.9',
    value: 'RECOMMENDED',
  },
  {
    label: 'Ceilling',
    description: 'Maximum Sale price.',
    example: '110.5',
    value: 'RECOMMENDED',
  },
  {
    label: 'Sellercost',
    description: 'Seller cost.',
    example: '30.54',
    value: 'RECOMMENDED',
  },
  {
    label: 'Inboundshippingcost',
    description: 'Shipping cost to the warehouse.',
    example: '7.39',
    value: 'RECOMMENDED',
  },
  {
    label: 'Othercosts',
    description: 'Other product costs.',
    example: '0',
    value: 'RECOMMENDED',
  },
  {
    label: 'Productiontime',
    description: 'Time to produce the product in days after the purchase order has been created.',
    example: '15',
    value: 'RECOMMENDED',
  },
  {
    label: 'Transittime',
    description: 'Time to ship the product to the warehouse in days after the product is already produce.',
    example: '35',
    value: 'RECOMMENDED',
  },
  {
    label: 'Shippingtofbacost',
    description: 'Shipping cost to the FBA warehouse.',
    example: '1.5',
    value: 'RECOMMENDED',
  },
  {
    label: 'Buffer',
    description: 'Quantity of products to keep in stock.',
    example: '3',
    value: 'RECOMMENDED',
  },
  {
    label: 'Itemcondition',
    description: 'The condition of the product. The condition must be in the reference data.',
    example: 'NEW',
    value: 'RECOMMENDED',
  },
  {
    label: 'Image',
    description: 'Product image URL.',
    example: '',
    value: 'REQUIRED',
  },
  {
    label: 'Days Of Stock',
    description: 'Days of Stock after lead time.',
    example: '',
    value: 'RECOMMENDED',
  },
]
