export const COMPARE_NUMBER_OPERATORS = [
  { value: '==', label: 'Equal' },
  { value: '!=', label: 'Not Equal' },
  { value: '>', label: 'Greater Than' },
  { value: '>=', label: 'Greater Than Or Equal' },
  { value: '<', label: 'Less Than' },
  { value: '<=', label: 'Less Than Or Equal' },
]

export const COMPARE_STRING_OPERATORS = [
  { value: '==', label: 'Equal' },
  { value: '!=', label: 'Not Equal' },
  { value: 'in', label: 'In' },
  { value: 'not in', label: 'Not In' },
  { value: 'contains', label: 'Contains' },
  { value: 'not contains', label: 'Not Contains' },
  { value: 'starts with', label: 'Starts With' },
  { value: 'ends with', label: 'Ends With' },
  { value: 'is null', label: 'Is Null' },
  { value: 'is not null', label: 'Is Not Null' },
  { value: 'between', label: 'Between' },
  { value: 'not between', label: 'Not Between' },
  { value: 'like', label: 'Like' },
  { value: 'not like', label: 'Not Like' },
  { value: 'is', label: 'Is' },
  { value: 'is not', label: 'Is Not' },
  { value: 'is empty', label: 'Is Empty' },
  { value: 'is not empty', label: 'Is Not Empty' },
  { value: 'is true', label: 'Is True' },
  { value: 'is false', label: 'Is False' },
  { value: 'is one of', label: 'Is One Of' },
  { value: 'is not one of', label: 'Is Not One Of' },
  { value: 'is any of', label: 'Is Any Of' },
  { value: 'is not any of', label: 'Is Not Any Of' },
  { value: 'is any', label: 'Is Any' },
  { value: 'is not any', label: 'Is Not Any' },
  { value: 'is all', label: 'Is All' },
  { value: 'is not all', label: 'Is Not All' },
]
