import { GetServerSideProps } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import { Col, Container, Row } from 'reactstrap'
import { getSession } from '@auth/client'
import BreadCrumb from '@components/Common/BreadCrumb'
import Widget from '@components/Widget'
import axios from 'axios'
import { useEffect, useState } from 'react'

export const getServerSideProps: GetServerSideProps<{}> = async (context) => {
  const session = await getSession(context)

  if (session == null) {
    return {
      redirect: {
        destination: '/api/auth/signin',
        permanent: false,
      },
    }
  }
  return {
    props: { session },
  }
}

const Home = () => {
  const [summary, setsummary] = useState({})
  
  useEffect(() => {
    const bringSummary = async () => {
      const response = await axios('/api/getBusinessSummary')
      setsummary(response.data)
    }
    bringSummary()
  }, [])

  return (
    <div>
      <Head>
        <title>Shipnovo Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="page-content">
        <Container fluid>
          <BreadCrumb title="Dashboard" pageTitle="Dashboards" />
          <Row>
            <Col xxl={5}>
              <Widget summary={summary} />
            </Col>
          </Row>
        </Container>
      </div>
    </div>
  )
}

export default Home
