/* eslint-disable react-hooks/exhaustive-deps */
import { useContext, useEffect, useState } from 'react'
import AppContext from '@context/AppContext'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { Col, Container, Row } from 'reactstrap'
import { getSession } from '@auth/client'
import BreadCrumb from '@components/Common/BreadCrumb'
import Widget from '@components/Widget'
import axios from 'axios'
import useSWR from 'swr'
import DashboardHeader from '@components/DashboardHeader'
import moment from 'moment'
import MostInvenotryList from '@components/MostInvenotryList'
import { Summary } from '@typings'
import TotalChagesList from '@components/TotalChagesList'
import InvoicesList from '@components/InvoicesList'
import { toast } from 'react-toastify'
import SalesOverTime from '@components/dashboard/SalesOverTime'

export const getServerSideProps: GetServerSideProps<{}> = async (context) => {
  const sessionToken = context.req.cookies['next-auth.session-token'] ? context.req.cookies['next-auth.session-token'] : context.req.cookies['__Secure-next-auth.session-token']

  const session = await getSession(context)

  if (session == null) {
    return {
      redirect: {
        destination: '/api/auth/signin',
        permanent: false,
      },
    }
  }
  return {
    props: { session, sessionToken },
  }
}

type Props = {
  sessionToken: string
  session: {
    user: {
      name: string
    }
  }
}

const Home = ({ session, sessionToken }: Props) => {
  const { state }: any = useContext(AppContext)
  const [loading, setLoading] = useState(true)
  const [summary, setSummary] = useState<Summary | null>()
  const [dashboardStartDate, setDashboardStartDate] = useState(moment().subtract(30, 'days').format('YYYY-MM-DD'))
  const [dashboardEndDate, setDashboardEndDate] = useState(moment().format('YYYY-MM-DD'))
  // const [selectedMarketplace, setSelectedMarketplace] = useState({ storeId: 9999, name: 'All Marketplaces', logo: '' })
  const [salesOverTime, setSalesOverTime] = useState<{ [key: string]: { [key: string]: number } }>({})
  const [loadingData, setLoadingData] = useState(true)

  const fetcher = (endPoint: string) => axios(endPoint).then((res) => res.data)
  const { data } = useSWR(
    state.user.businessId
      ? `/api/getBusinessSummary?region=${state.currentRegion}&businessId=${state.user.businessId}&startDate=${dashboardStartDate}&endDate=${dashboardEndDate}`
      : null,
    fetcher
  )

  useEffect(() => {
    const controller = new AbortController()
    const signal = controller.signal

    const getNewDateRange = async () => {
      setLoadingData(true)
      await axios(
        `${process.env.NEXT_PUBLIC_SHELFCLOUD_SERVER_URL}/api/orders/getSalesOverTime?region=${state.currentRegion}&businessId=${state.user.businessId}&startDate=${dashboardStartDate}&endDate=${dashboardEndDate}&storeId=9999`,
        {
          signal,
          headers: {
            Authorization: `Bearer ${sessionToken}`,
          },
        }
      )
        .then((res) => {
          setSalesOverTime(res.data as { [key: string]: { [key: string]: number } })
          setLoadingData(false)
        })
        .catch(({ error }) => {
          if (axios.isCancel(error)) {
            toast.error(error?.data?.message || 'Error fetching product performance data')
            setSalesOverTime({})
          }
        })
    }
    if (session && state.user.businessId) getNewDateRange()

    return () => {
      controller.abort()
    }
  }, [session, state.user.businessId, dashboardEndDate])

  const handleChangeDates = (dateStr: string) => {
    if (dateStr.includes(' to ')) {
      const dates = dateStr.split(' to ')
      setDashboardStartDate(moment(dates[0], 'DD MMM YY').format('YYYY-MM-DD'))
      setDashboardEndDate(moment(dates[1], 'DD MMM YY').format('YYYY-MM-DD'))
    }
  }

  useEffect(() => {
    if (data?.error) {
      setSummary(null)
      setLoading(false)
      toast.error(data?.message)
    } else if (data) {
      setSummary(data)
      setLoading(false)
    }
  }, [data])

  return (
    <div>
      <Head>
        <title>Shelf Cloud Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='page-content'>
        <Container fluid>
          <BreadCrumb title='Dashboard' pageTitle='Dashboards' />
          <Row>
            <Col>
              <DashboardHeader user={state.user.name} handleChangeDates={handleChangeDates} startDate={dashboardStartDate} endDate={dashboardEndDate} />
              {!loading ? (
                <>
                  <Row>
                    <Widget summary={summary} />
                  </Row>
                  <Row>
                    <Col md={7}>
                      {loadingData ? null : <SalesOverTime salesOverTime={salesOverTime} loadingData={loadingData} />}
                      <MostInvenotryList products={summary?.mostInventory} />
                    </Col>
                    <Col md={5}>
                      <TotalChagesList totalCharges={summary?.totalCharges} />
                      <InvoicesList invoices={summary?.invoices} />
                    </Col>
                  </Row>
                </>
              ) : (
                <Row>
                  <h5>Loading...</h5>
                </Row>
              )}
            </Col>
          </Row>
        </Container>
      </div>
    </div>
  )
}

export default Home
