import { useContext, useEffect, useState } from 'react'
import AppContext from '@context/AppContext'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import { Col, Container, Row } from 'reactstrap'
import { getSession } from '@auth/client'
import BreadCrumb from '@components/Common/BreadCrumb'
import Widget from '@components/Widget'
import axios from 'axios'
import useSWR from 'swr'
import DashboardHeader from '@components/DashboardHeader'
import moment from 'moment'
import MostInvenotryList from '@components/MostInvenotryList'
import { Summary } from '@typings'
import TotalChagesList from '@components/TotalChagesList'

export const getServerSideProps: GetServerSideProps<{}> = async (context) => {
  const session = await getSession(context)

  if (session == null) {
    return {
      redirect: {
        destination: '/api/auth/signin',
        permanent: false,
      },
    }
  }
  return {
    props: { session },
  }
}

const Home = () => {
  const { state }: any = useContext(AppContext)
  const [summary, setSummary] = useState<Summary>()
  const [dashboardStartDate, setDashboardStartDate] = useState(
    moment().subtract(30, 'days').format('YYYY-MM-DD')
  )
  const [dashboardEndDate, setDashboardEndDate] = useState(
    moment().format('YYYY-MM-DD')
  )

  const fetcher = (endPoint: string) => axios(endPoint).then((res) => res.data)
  const { data, error } = useSWR(
    state.user.businessId
      ? `/api/getBusinessSummary?businessId=${state.user.businessId}&startDate=${dashboardStartDate}&endDate=${dashboardEndDate}`
      : null,
    fetcher
  )

  const handleChangeDates = (dateStr: string) => {
    if (dateStr.includes(' to ')) {
      const dates = dateStr.split(' to ')
      setDashboardStartDate(moment(dates[0], 'DD-MM-YYYY').format('YYYY-MM-DD'))
      setDashboardEndDate(moment(dates[1], 'DD-MM-YYYY').format('YYYY-MM-DD'))
    }
  }

  useEffect(() => {
    if (data) {
      setSummary(data)
    }
  }, [data])

  return (
    <div>
      <Head>
        <title>Shipnovo Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="page-content">
        <Container fluid>
          <BreadCrumb title="Dashboard" pageTitle="Dashboards" />
          <Row>
            <Col>
              <DashboardHeader
                user={state.user.name}
                handleChangeDates={handleChangeDates}
                startDate={dashboardStartDate}
                endDate={dashboardEndDate}
              />
              <Row>
                <Widget summary={summary} />
              </Row>
              <Row>
                <MostInvenotryList products={summary?.mostInventory} />
                <TotalChagesList totalCharges={summary?.totalCharges}/>
              </Row>
            </Col>
          </Row>
        </Container>
      </div>
    </div>
  )
}

export default Home
