export const MARKETPLACE_NAME_LIST: string[] = [
  '123Stores',
  '1800 Flowers',
  'Academy Sports + Outdoors',
  'Ace',
  'Amazon Dropship',
  'Amazon Marketplace',
  'Amazon Vendor',
  'Babylist',
  'Back Market',
  'Bass Pro Shops',
  'Bed Bath & Beyond',
  'Belk',
  'Best Buy Dropship',
  'Best Buy Marketplace',
  'BigCommerce',
  "BJ's",
  "Bloomingdale's",
  'Bluestem',
  'Bonanza',
  'Burlington',
  'Cdiscount',
  'Chewy Dropship',
  'Costco',
  'Crate & Barrel',
  'Daily Steals',
  "DICK'S Sporting Goods",
  'Dormify',
  'eBay',
  'Ethan Allen',
  'Etsy',
  'Exchange',
  'Faire',
  'Fanatics',
  'Fruugo',
  'Giant Eagle',
  'Google Shopping',
  'Groupon',
  'GunBroker',
  "Harper's Bazaar",
  'Hayneedle',
  'Home Depot',
  'HomeGoods',
  'Houzz',
  'HSN',
  'Indigo Books & Music',
  'JCPenney',
  'Kmart',
  "Kohl's",
  'Kroger',
  'Lord & Taylor',
  "Lowe's",
  "Macy's",
  'Magento',
  'Maisonette',
  'Marshalls',
  'Mason',
  'Meijer',
  'Mercado Libre',
  'Michaels',
  'Moda Operandi',
  'NBC Universal',
  'Neiman Marcus',
  'Newegg',
  'NocNoc',
  'Nordstrom',
  'OpenSky',
  'Oriental Trading',
  'Peapod Digital Labs',
  'Pet Supplies Plus',
  'Petco',
  'PetSmart',
  'PremStar',
  'PrestaShop',
  'Pricefalls',
  'Purchasing Power',
  'QVC',
  'Rakuten',
  'Reebelo',
  'Rogers & Hollands',
  'Ross-Simons',
  'Rue Gilt Groupe',
  'Saks',
  "Sam's Club",
  'Scheels',
  'Sears',
  'Shein',
  'Shop HQ',
  'Shop Premium Outlets',
  'Shopify',
  'Shopping Cart',
  'Snappy',
  'Staples',
  'Sysco',
  'Tanga',
  'Target',
  'Target Plus',
  'Temu',
  'The Knot',
  'The Range',
  'The Tot',
  'Tiendamia',
  'TikTok',
  'TJ Maxx',
  'Tophatter',
  'Toys R Us',
  'Tractor Supply',
  'Verishop',
  'VirVentures',
  'Walmart Dropship',
  'Walmart Marketplace',
  'Walmart Vendor',
  'Wayfair',
  'Webstaurant',
  'Wholesale',
  'Wish.com',
  'WooCommerce',
  'Zoro',
]
